### PR TITLE
Fix build with Clang 15

### PR DESCRIPTION
**Pull request by fw-immunant**
Updated my machine and ran into an API change.

### CODE REVIEW

**Comment by ayrtonm** [comment]
The change looks fine to me, but can we add clang 15 to CI?

**Review by ayrtonm — APPROVED** [review]

**Comment by fw-immunant** [comment]
I hesitated because we also don't have Clang 14 in CI...

**Comment by fw-immunant** [comment]
I'll follow up with a PR to see what explodes adding Clang 14+15 to CI.

**Comment by ayrtonm** [comment]
#179 probably isn't the most important thing to debug at the moment but thanks for opening the PR so we at least know what the state of it it.

**Pull request merged**
