### PR TITLE
Merge `nginx` into `main` and add it to CI

### PR DESCRIPTION
**Pull request by endbr64**
Tested on `donna` using:

```
mkdir build && cd build
cmake .. -DClang_DIR=/usr/lib/cmake/clang-14 -DLLVM_DIR=/usr/lib/llvm-14/cmake -DLLVM_EXTERNAL_LIT=`which lit` -DLIBIA2_INSECURE=OFF -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -G Ninja
ninja check-ia2

cd ../external/nginx
./reconfigure
make -j`nproc`

./build/nginx
curl localhost:8001
```

### CODE REVIEW

**Comment by rinon** [comment]
What is the status of this? Are we waiting for the source rewriter to land?

**Comment by endbr64** [comment]
I mentioned a while back in an IA2 meeting that it doesn't make sense to merge this PR anymore:

* Source rewriter makes all the pointer changes obsolete. Ayrton is working on wrapping nginx using the new way in #188.
* You mentioned that `dlopen()` may no longer make sense to support.
* Partition Alloc integration is not part of this PR and continues elsewhere.

**Comment by rinon** [comment]
Ack, sounds good, just wasn't sure if it made sense to put this in first. We can hold off until those other pieces are ready.

**Comment by rinon** [comment]
afaict this PR is stale and no longer needed with other things that have landed. Is that correct, @endbr64 ? If so, can we close it?

**Comment by endbr64** [comment]
Yes, let me do that.

**Pull request closed without merging**
